pub fn ill() { unimplemented!(); }
pub fn ret() { unimplemented!(); }
pub fn retw() { unimplemented!(); }
pub fn jx() { unimplemented!(); }
pub fn callx0() { unimplemented!(); }
pub fn callx4() { unimplemented!(); }
pub fn callx8() { unimplemented!(); }
pub fn callx12() { unimplemented!(); }
pub fn movsp() { unimplemented!(); }
pub fn isync() { unimplemented!(); }
pub fn rsync() { unimplemented!(); }
pub fn esync() { unimplemented!(); }
pub fn dsync() { unimplemented!(); }
pub fn excw() { unimplemented!(); }
pub fn memw() { unimplemented!(); }
pub fn extw() { unimplemented!(); }
pub fn rfe() { unimplemented!(); }
pub fn rfue() { unimplemented!(); }
pub fn rfde() { unimplemented!(); }
pub fn rfwo() { unimplemented!(); }
pub fn rfwu() { unimplemented!(); }
pub fn rfi() { unimplemented!(); }
pub fn rfme() { unimplemented!(); }
pub fn r#break() { unimplemented!(); }
pub fn syscall() { unimplemented!(); }
pub fn rsil() { unimplemented!(); }
pub fn waiti() { unimplemented!(); }
pub fn any4() { unimplemented!(); }
pub fn all4() { unimplemented!(); }
pub fn any8() { unimplemented!(); }
pub fn all8() { unimplemented!(); }
pub fn and() { unimplemented!(); }
pub fn or() { unimplemented!(); }
pub fn xor() { unimplemented!(); }
pub fn ssr() { unimplemented!(); }
pub fn ssl() { unimplemented!(); }
pub fn ssa8l() { unimplemented!(); }
pub fn ssa8b() { unimplemented!(); }
pub fn ssai() { unimplemented!(); }
pub fn rer() { unimplemented!(); }
pub fn wer() { unimplemented!(); }
pub fn rotw() { unimplemented!(); }
pub fn nsa() { unimplemented!(); }
pub fn nsau() { unimplemented!(); }
pub fn ritlb0() { unimplemented!(); }
pub fn iitlb() { unimplemented!(); }
pub fn pitlb() { unimplemented!(); }
pub fn witlb() { unimplemented!(); }
pub fn ritlb1() { unimplemented!(); }
pub fn rdtlb0() { unimplemented!(); }
pub fn idtlb() { unimplemented!(); }
pub fn pdtlb() { unimplemented!(); }
pub fn wdtlb() { unimplemented!(); }
pub fn rdtlb1() { unimplemented!(); }
pub fn neg() { unimplemented!(); }
pub fn abs() { unimplemented!(); }
pub fn add() { unimplemented!(); }
pub fn addx2() { unimplemented!(); }
pub fn addx4() { unimplemented!(); }
pub fn addx8() { unimplemented!(); }
pub fn sub() { unimplemented!(); }
pub fn sub2() { unimplemented!(); }
pub fn sub4() { unimplemented!(); }
pub fn sub8() { unimplemented!(); }
pub fn slli() { unimplemented!(); }
pub fn srai() { unimplemented!(); }
pub fn srli() { unimplemented!(); }
pub fn xsr() { unimplemented!(); }
pub fn src() { unimplemented!(); }
pub fn srl() { unimplemented!(); }
pub fn sll() { unimplemented!(); }
pub fn sra() { unimplemented!(); }
pub fn mul16u() { unimplemented!(); }
pub fn mul16s() { unimplemented!(); }
pub fn lict() { unimplemented!(); }
pub fn sict() { unimplemented!(); }
pub fn licw() { unimplemented!(); }
pub fn sicw() { unimplemented!(); }
pub fn ldct() { unimplemented!(); }
pub fn sdct() { unimplemented!(); }
pub fn rfdo() { unimplemented!(); }
pub fn rfd0() { unimplemented!(); }
pub fn rfdd() { unimplemented!(); }
pub fn andbc() { unimplemented!(); }
pub fn orb() { unimplemented!(); }
pub fn orbc() { unimplemented!(); }
pub fn xorb() { unimplemented!(); }
pub fn mull() { unimplemented!(); }
pub fn muluh() { unimplemented!(); }
pub fn mulsh() { unimplemented!(); }
pub fn quou() { unimplemented!(); }
pub fn quos() { unimplemented!(); }
pub fn remu() { unimplemented!(); }
pub fn rems() { unimplemented!(); }
pub fn rsr() { unimplemented!(); }
pub fn wsr() { unimplemented!(); }
pub fn sext() { unimplemented!(); }
pub fn clamps() { unimplemented!(); }
pub fn min() { unimplemented!(); }
pub fn max() { unimplemented!(); }
pub fn minu() { unimplemented!(); }
pub fn maxu() { unimplemented!(); }
pub fn moveqz() { unimplemented!(); }
pub fn movnez() { unimplemented!(); }
pub fn movltz() { unimplemented!(); }
pub fn mozgez() { unimplemented!(); }
pub fn movf() { unimplemented!(); }
pub fn movt() { unimplemented!(); }
pub fn rur() { unimplemented!(); }
pub fn wur() { unimplemented!(); }
pub fn extui() { unimplemented!(); }
pub fn lsx() { unimplemented!(); }
pub fn lsxu() { unimplemented!(); }
pub fn ssx() { unimplemented!(); }
pub fn ssxu() { unimplemented!(); }
pub fn l32e() { unimplemented!(); }
pub fn s32e() { unimplemented!(); }
pub fn add_s() { unimplemented!(); }
pub fn sub_s() { unimplemented!(); }
pub fn mul_s() { unimplemented!(); }
pub fn madd_s() { unimplemented!(); }
pub fn msub_s() { unimplemented!(); }
pub fn round_s() { unimplemented!(); }
pub fn trunc_s() { unimplemented!(); }
pub fn floor_s() { unimplemented!(); }
pub fn ceil_s() { unimplemented!(); }
pub fn float_s() { unimplemented!(); }
pub fn ufloat_s() { unimplemented!(); }
pub fn utrunc_s() { unimplemented!(); }
pub fn mov_s() { unimplemented!(); }
pub fn abs_s() { unimplemented!(); }
pub fn rfr() { unimplemented!(); }
pub fn wfr() { unimplemented!(); }
pub fn neg_s() { unimplemented!(); }
pub fn un_s() { unimplemented!(); }
pub fn qeq_s() { unimplemented!(); }
pub fn ueq_s() { unimplemented!(); }
pub fn olt_s() { unimplemented!(); }
pub fn ult_s() { unimplemented!(); }
pub fn ole_s() { unimplemented!(); }
pub fn ule_s() { unimplemented!(); }
pub fn moveqz_s() { unimplemented!(); }
pub fn movnez_s() { unimplemented!(); }
pub fn movltz_s() { unimplemented!(); }
pub fn movgez_z() { unimplemented!(); }
pub fn movf_s() { unimplemented!(); }
pub fn movt_s() { unimplemented!(); }
pub fn l32r() { unimplemented!(); }
pub fn l8ui() { unimplemented!(); }
pub fn l16ui() { unimplemented!(); }
pub fn l32ui() { unimplemented!(); }
pub fn s8i() { unimplemented!(); }
pub fn s16i() { unimplemented!(); }
pub fn s32i() { unimplemented!(); }
pub fn l16si() { unimplemented!(); }
pub fn movi() { unimplemented!(); }
pub fn l32ai() { unimplemented!(); }
pub fn addi() { unimplemented!(); }
pub fn addmi() { unimplemented!(); }
pub fn s32c1i() { unimplemented!(); }
pub fn s32ri() { unimplemented!(); }
pub fn dpfr() { unimplemented!(); }
pub fn dpfw() { unimplemented!(); }
pub fn dpfro() { unimplemented!(); }
pub fn dpfwo() { unimplemented!(); }
pub fn dhwb() { unimplemented!(); }
pub fn dhwbi() { unimplemented!(); }
pub fn dhi() { unimplemented!(); }
pub fn dii() { unimplemented!(); }
pub fn ipf() { unimplemented!(); }
pub fn ihi() { unimplemented!(); }
pub fn iii() { unimplemented!(); }
pub fn dpfl() { unimplemented!(); }
pub fn dhu() { unimplemented!(); }
pub fn diu() { unimplemented!(); }
pub fn diwb() { unimplemented!(); }
pub fn diwbi() { unimplemented!(); }
pub fn ipfl() { unimplemented!(); }
pub fn ihu() { unimplemented!(); }
pub fn iiu() { unimplemented!(); }
pub fn lsi() { unimplemented!(); }
pub fn ssi() { unimplemented!(); }
pub fn lsiu() { unimplemented!(); }
pub fn ssiu() { unimplemented!(); }
pub fn mula_dd_ll_ldinc() { unimplemented!(); }
pub fn mula_dd_hl_ldinc() { unimplemented!(); }
pub fn mula_dd_lh_ldinc() { unimplemented!(); }
pub fn mula_dd_hh_ldinc() { unimplemented!(); }
pub fn mula_dd_ll_lddec() { unimplemented!(); }
pub fn mula_dd_hl_lddec() { unimplemented!(); }
pub fn mula_dd_lh_lddec() { unimplemented!(); }
pub fn mula_dd_hh_lddec() { unimplemented!(); }
pub fn mul_dd_ll() { unimplemented!(); }
pub fn mul_dd_hl() { unimplemented!(); }
pub fn mul_dd_lh() { unimplemented!(); }
pub fn mul_dd_hh() { unimplemented!(); }
pub fn mula_dd_ll() { unimplemented!(); }
pub fn mula_dd_hl() { unimplemented!(); }
pub fn mula_dd_lh() { unimplemented!(); }
pub fn mula_dd_hh() { unimplemented!(); }
pub fn muls_dd_ll() { unimplemented!(); }
pub fn muls_dd_hl() { unimplemented!(); }
pub fn muls_dd_lh() { unimplemented!(); }
pub fn muls_dd_hh() { unimplemented!(); }
pub fn mul_ad_ll() { unimplemented!(); }
pub fn mul_ad_hl() { unimplemented!(); }
pub fn mul_ad_lh() { unimplemented!(); }
pub fn mul_ad_hh() { unimplemented!(); }
pub fn mula_ad_ll() { unimplemented!(); }
pub fn mula_ad_hl() { unimplemented!(); }
pub fn mula_ad_lh() { unimplemented!(); }
pub fn mula_ad_hh() { unimplemented!(); }
pub fn muls_ad_ll() { unimplemented!(); }
pub fn muls_ad_hl() { unimplemented!(); }
pub fn muls_ad_lh() { unimplemented!(); }
pub fn muls_ad_hh() { unimplemented!(); }
pub fn mula_da_ll_ldinc() { unimplemented!(); }
pub fn mula_da_hl_ldinc() { unimplemented!(); }
pub fn mula_da_lh_ldinc() { unimplemented!(); }
pub fn mula_da_hh_ldinc() { unimplemented!(); }
pub fn mula_da_ll_lddec() { unimplemented!(); }
pub fn mula_da_hl_lddec() { unimplemented!(); }
pub fn mula_da_lh_lddec() { unimplemented!(); }
pub fn mula_da_hh_lddec() { unimplemented!(); }
pub fn mul_da_ll() { unimplemented!(); }
pub fn mul_da_hl() { unimplemented!(); }
pub fn mul_da_lh() { unimplemented!(); }
pub fn mul_da_hh() { unimplemented!(); }
pub fn mula_da_ll() { unimplemented!(); }
pub fn mula_da_hl() { unimplemented!(); }
pub fn mula_da_lh() { unimplemented!(); }
pub fn mula_da_hh() { unimplemented!(); }
pub fn muls_da_ll() { unimplemented!(); }
pub fn muls_da_hl() { unimplemented!(); }
pub fn muls_da_lh() { unimplemented!(); }
pub fn muls_da_hh() { unimplemented!(); }
pub fn umul_aa_ll() { unimplemented!(); }
pub fn umul_aa_hl() { unimplemented!(); }
pub fn umul_aa_lh() { unimplemented!(); }
pub fn umul_aa_hh() { unimplemented!(); }
pub fn mul_aa_ll() { unimplemented!(); }
pub fn mul_aa_hl() { unimplemented!(); }
pub fn mul_aa_lh() { unimplemented!(); }
pub fn mul_aa_hh() { unimplemented!(); }
pub fn mula_aa_ll() { unimplemented!(); }
pub fn mula_aa_hl() { unimplemented!(); }
pub fn mula_aa_lh() { unimplemented!(); }
pub fn mula_aa_hh() { unimplemented!(); }
pub fn muls_aa_ll() { unimplemented!(); }
pub fn muls_aa_hl() { unimplemented!(); }
pub fn muls_aa_lh() { unimplemented!(); }
pub fn muls_aa_hh() { unimplemented!(); }
pub fn ldinc() { unimplemented!(); }
pub fn lddec() { unimplemented!(); }
pub fn call0() { unimplemented!(); }
pub fn call4() { unimplemented!(); }
pub fn call8() { unimplemented!(); }
pub fn call12() { unimplemented!(); }
pub fn j() { unimplemented!(); }
pub fn bz() { unimplemented!(); }
pub fn beqi() { unimplemented!(); }
pub fn bnei() { unimplemented!(); }
pub fn blti() { unimplemented!(); }
pub fn bgei() { unimplemented!(); }
pub fn entry() { unimplemented!(); }
pub fn bf() { unimplemented!(); }
pub fn bt() { unimplemented!(); }
pub fn r#loop() { unimplemented!(); }
pub fn loopnez() { unimplemented!(); }
pub fn loopgtz() { unimplemented!(); }
pub fn bnone() { unimplemented!(); }
pub fn beq() { unimplemented!(); }
pub fn blt() { unimplemented!(); }
pub fn bltu() { unimplemented!(); }
pub fn ball() { unimplemented!(); }
pub fn bbc() { unimplemented!(); }
pub fn bbci() { unimplemented!(); }
pub fn bany() { unimplemented!(); }
pub fn bne() { unimplemented!(); }
pub fn bge() { unimplemented!(); }
pub fn bgeu() { unimplemented!(); }
pub fn bnall() { unimplemented!(); }
pub fn bbs() { unimplemented!(); }
pub fn bbsi() { unimplemented!(); }
pub fn movi_n() { unimplemented!(); }
pub fn beqz_n() { unimplemented!(); }
pub fn bnez_n() { unimplemented!(); }
pub fn bltui() { unimplemented!(); }
pub fn bgeui() { unimplemented!(); }
pub fn l32r_n() { unimplemented!(); }
pub fn s32i_n() { unimplemented!(); }
pub fn add_n() { unimplemented!(); }
pub fn addi_n() { unimplemented!(); }
pub fn mov_n() { unimplemented!(); }
pub fn ret_n() { unimplemented!(); }
pub fn retw_n() { unimplemented!(); }
pub fn break_n() { unimplemented!(); }
pub fn nop_n() { unimplemented!(); }
