use crate::syntax;
use falcon::{
    self,
    architecture::Endian,
    il::*,
    translator::{BlockTranslationResult, Translator},
};

mod semantics;

pub enum Error {
    Syntax(syntax::Error),
    Eof,
}

#[derive(Debug)]
pub struct XtensaLx6Le;

#[derive(Debug)]
pub struct XtensaLx6Be;

fn translate_block(bytes: &[u8], address: u64, endian: Endian) -> falcon::Result<BlockTranslationResult> {
    // A vec which holds each lifted instruction in this block.
    let mut block_graphs: Vec<(u64, ControlFlowGraph)> = Vec::new();

    // the length of this block in bytes.
    let mut length: usize = 0;

    // The successors which exit this block.
    let mut successors = Vec::new();

    // Offset in bytes to the next instruction from the address given at entry.
    let mut offset: usize = 0;

    loop {
        if offset >= bytes.len() {
            unimplemented!()
        }

        let disassembly_range = (offset)..bytes.len();
        let disassembly_bytes = bytes.get(disassembly_range).unwrap();

        let instruction = match endian {
            Endian::Little => match_opcode_le(disassembly_bytes),
            Endian::Big => match_opcode_le(disassembly_bytes),
        };

        match instruction.id {
            syntax::Id::ILL => semantics::ill(),
            syntax::Id::RET => semantics::ret(),
            syntax::Id::RETW => semantics::retw(),
            syntax::Id::JX => semantics::jx(),
            syntax::Id::CALLX0 => semantics::callx0(),
            syntax::Id::CALLX4 => semantics::callx4(),
            syntax::Id::CALLX8 => semantics::callx8(),
            syntax::Id::CALLX12 => semantics::callx12(),
            syntax::Id::MOVSP => semantics::movsp(),
            syntax::Id::ISYNC => semantics::isync(),
            syntax::Id::RSYNC => semantics::rsync(),
            syntax::Id::ESYNC => semantics::esync(),
            syntax::Id::DSYNC => semantics::dsync(),
            syntax::Id::EXCW => semantics::excw(),
            syntax::Id::MEMW => semantics::memw(),
            syntax::Id::EXTW => semantics::extw(),
            syntax::Id::RFE => semantics::rfe(),
            syntax::Id::RFUE => semantics::rfue(),
            syntax::Id::RFDE => semantics::rfde(),
            syntax::Id::RFWO => semantics::rfwo(),
            syntax::Id::RFWU => semantics::rfwu(),
            syntax::Id::RFI => semantics::rfi(),
            syntax::Id::RFME => semantics::rfme(),
            syntax::Id::BREAK => semantics::r#break(),
            syntax::Id::SYSCALL => semantics::syscall(),
            syntax::Id::RSIL => semantics::rsil(),
            syntax::Id::WAITI => semantics::waiti(),
            syntax::Id::ANY4 => semantics::any4(),
            syntax::Id::ALL4 => semantics::all4(),
            syntax::Id::ANY8 => semantics::any8(),
            syntax::Id::ALL8 => semantics::all8(),
            syntax::Id::AND => semantics::and(),
            syntax::Id::OR => semantics::or(),
            syntax::Id::XOR => semantics::xor(),
            syntax::Id::SSR => semantics::ssr(),
            syntax::Id::SSL => semantics::ssl(),
            syntax::Id::SSA8L => semantics::ssa8l(),
            syntax::Id::SSA8B => semantics::ssa8b(),
            syntax::Id::SSAI => semantics::ssai(),
            syntax::Id::RER => semantics::rer(),
            syntax::Id::WER => semantics::wer(),
            syntax::Id::ROTW => semantics::rotw(),
            syntax::Id::NSA => semantics::nsa(),
            syntax::Id::NSAU => semantics::nsau(),
            syntax::Id::RITLB0 => semantics::ritlb0(),
            syntax::Id::IITLB => semantics::iitlb(),
            syntax::Id::PITLB => semantics::pitlb(),
            syntax::Id::WITLB => semantics::witlb(),
            syntax::Id::RITLB1 => semantics::ritlb1(),
            syntax::Id::RDTLB0 => semantics::rdtlb0(),
            syntax::Id::IDTLB => semantics::idtlb(),
            syntax::Id::PDTLB => semantics::pdtlb(),
            syntax::Id::WDTLB => semantics::wdtlb(),
            syntax::Id::RDTLB1 => semantics::rdtlb1(),
            syntax::Id::NEG => semantics::neg(),
            syntax::Id::ABS => semantics::abs(),
            syntax::Id::ADD => semantics::add(),
            syntax::Id::ADDX2 => semantics::addx2(),
            syntax::Id::ADDX4 => semantics::addx4(),
            syntax::Id::ADDX8 => semantics::addx8(),
            syntax::Id::SUB => semantics::sub(),
            syntax::Id::SUBX2 => semantics::sub2(),
            syntax::Id::SUBX4 => semantics::sub4(),
            syntax::Id::SUBX8 => semantics::sub8(),
            syntax::Id::SLLI => semantics::slli(),
            syntax::Id::SRAI => semantics::srai(),
            syntax::Id::SRLI => semantics::srli(),
            syntax::Id::XSR => semantics::xsr(),
            syntax::Id::SRC => semantics::src(),
            syntax::Id::SRL => semantics::srl(),
            syntax::Id::SLL => semantics::sll(),
            syntax::Id::SRA => semantics::sra(),
            syntax::Id::MUL16U => semantics::mul16u(),
            syntax::Id::MUL16S => semantics::mul16s(),
            syntax::Id::LICT => semantics::lict(),
            syntax::Id::SICT => semantics::sict(),
            syntax::Id::LICW => semantics::licw(),
            syntax::Id::SICW => semantics::sicw(),
            syntax::Id::LDCT => semantics::ldct(),
            syntax::Id::SDCT => semantics::sdct(),
            syntax::Id::RFDO => semantics::rfdo(),
            syntax::Id::RFDD => semantics::rfd0(),
            syntax::Id::ANDB => semantics::rfdd(),
            syntax::Id::ANDBC => semantics::andbc(),
            syntax::Id::ORB => semantics::orb(),
            syntax::Id::ORBC => semantics::orbc(),
            syntax::Id::XORB => semantics::xorb(),
            syntax::Id::MULL => semantics::mull(),
            syntax::Id::MULUH => semantics::muluh(),
            syntax::Id::MULSH => semantics::mulsh(),
            syntax::Id::QUOU => semantics::quou(),
            syntax::Id::QUOS => semantics::quos(),
            syntax::Id::REMU => semantics::remu(),
            syntax::Id::REMS => semantics::rems(),
            syntax::Id::RSR => semantics::rsr(),
            syntax::Id::WSR => semantics::wsr(),
            syntax::Id::SEXT => semantics::sext(),
            syntax::Id::CLAMPS => semantics::clamps(),
            syntax::Id::MIN => semantics::min(),
            syntax::Id::MAX => semantics::max(),
            syntax::Id::MINU => semantics::minu(),
            syntax::Id::MAXU => semantics::maxu(),
            syntax::Id::MOVEQZ => semantics::moveqz(),
            syntax::Id::MOVNEZ => semantics::movnez(),
            syntax::Id::MOVLTZ => semantics::movltz(),
            syntax::Id::MOVGEZ => semantics::mozgez(),
            syntax::Id::MOVF => semantics::movf(),
            syntax::Id::MOVT => semantics::movt(),
            syntax::Id::RUR => semantics::rur(),
            syntax::Id::WUR => semantics::wur(),
            syntax::Id::EXTUI => semantics::extui(),
            syntax::Id::LSX => semantics::lsx(),
            syntax::Id::LSXU => semantics::lsxu(),
            syntax::Id::SSX => semantics::ssx(),
            syntax::Id::SSXU => semantics::ssxu(),
            syntax::Id::L32E => semantics::l32e(),
            syntax::Id::S32E => semantics::s32e(),
            syntax::Id::ADD_S => semantics::add_s(),
            syntax::Id::SUB_S => semantics::sub_s(),
            syntax::Id::MUL_S => semantics::mul_s(),
            syntax::Id::MADD_S => semantics::madd_s(),
            syntax::Id::MSUB_S => semantics::msub_s(),
            syntax::Id::ROUND_S => semantics::round_s(),
            syntax::Id::TRUNC_S => semantics::trunc_s(),
            syntax::Id::FLOOR_S => semantics::floor_s(),
            syntax::Id::CEIL_S => semantics::ceil_s(),
            syntax::Id::FLOAT_S => semantics::float_s(),
            syntax::Id::UFLOAT_S => semantics::ufloat_s(),
            syntax::Id::UTRUNC_S => semantics::utrunc_s(),
            syntax::Id::MOV_S => semantics::mov_s(),
            syntax::Id::ABS_S => semantics::abs_s(),
            syntax::Id::RFR => semantics::rfr(),
            syntax::Id::WFR => semantics::wfr(),
            syntax::Id::NEG_S => semantics::neg_s(),
            syntax::Id::UN_S => semantics::un_s(),
            syntax::Id::QEQ_S => semantics::qeq_s(),
            syntax::Id::UEQ_S => semantics::ueq_s(),
            syntax::Id::OLT_S => semantics::olt_s(),
            syntax::Id::ULT_S => semantics::ult_s(),
            syntax::Id::OLE_S => semantics::ole_s(),
            syntax::Id::ULE_S => semantics::ule_s(),
            syntax::Id::MOVEQZ_S => semantics::moveqz_s(),
            syntax::Id::MOVNEZ_S => semantics::movnez_s(),
            syntax::Id::MOVLTZ_S => semantics::movltz_s(),
            syntax::Id::MOVGEZ_S => semantics::movgez_z(),
            syntax::Id::MOVF_S => semantics::movf_s(),
            syntax::Id::MOVT_S => semantics::movt_s(),
            syntax::Id::L32R => semantics::l32r(),
            syntax::Id::L8UI => semantics::l8ui(),
            syntax::Id::L16UI => semantics::l16ui(),
            syntax::Id::L32UI => semantics::l32ui(),
            syntax::Id::S8I => semantics::s8i(),
            syntax::Id::S16I => semantics::s16i(),
            syntax::Id::S32I => semantics::s32i(),
            syntax::Id::L16SI => semantics::l16si(),
            syntax::Id::MOVI => semantics::movi(),
            syntax::Id::L32AI => semantics::l32ai(),
            syntax::Id::ADDI => semantics::addi(),
            syntax::Id::ADDMI => semantics::addmi(),
            syntax::Id::S32C1I => semantics::s32c1i(),
            syntax::Id::S32RI => semantics::s32ri(),
            syntax::Id::DPFR => semantics::dpfr(),
            syntax::Id::DPFW => semantics::dpfw(),
            syntax::Id::DPFRO => semantics::dpfro(),
            syntax::Id::DPFWO => semantics::dpfwo(),
            syntax::Id::DHWB => semantics::dhwb(),
            syntax::Id::DHWBI => semantics::dhwbi(),
            syntax::Id::DHI => semantics::dhi(),
            syntax::Id::DII => semantics::dii(),
            syntax::Id::IPF => semantics::ipf(),
            syntax::Id::IHI => semantics::ihi(),
            syntax::Id::III => semantics::iii(),
            syntax::Id::DPFL => semantics::dpfl(),
            syntax::Id::DHU => semantics::dhu(),
            syntax::Id::DIU => semantics::diu(),
            syntax::Id::DIWB => semantics::diwb(),
            syntax::Id::DIWBI => semantics::diwbi(),
            syntax::Id::IPFL => semantics::ipfl(),
            syntax::Id::IHU => semantics::ihu(),
            syntax::Id::IIU => semantics::iiu(),
            syntax::Id::LSI => semantics::lsi(),
            syntax::Id::SSI => semantics::ssi(),
            syntax::Id::LSIU => semantics::lsiu(),
            syntax::Id::SSIU => semantics::ssiu(),
            syntax::Id::MULA_DD_LL_LDINC => semantics::mula_dd_ll_ldinc(),
            syntax::Id::MULA_DD_HL_LDINC => semantics::mula_dd_hl_ldinc(),
            syntax::Id::MULA_DD_LH_LDINC => semantics::mula_dd_lh_ldinc(),
            syntax::Id::MULA_DD_HH_LDINC => semantics::mula_dd_hh_ldinc(),
            syntax::Id::MULA_DD_LL_LDDEC => semantics::mula_dd_ll_lddec(),
            syntax::Id::MULA_DD_HL_LDDEC => semantics::mula_dd_hl_lddec(),
            syntax::Id::MULA_DD_LH_LDDEC => semantics::mula_dd_lh_lddec(),
            syntax::Id::MULA_DD_HH_LDDEC => semantics::mula_dd_hh_lddec(),
            syntax::Id::MUL_DD_LL => semantics::mul_dd_ll(),
            syntax::Id::MUL_DD_HL => semantics::mul_dd_hl(),
            syntax::Id::MUL_DD_LH => semantics::mul_dd_lh(),
            syntax::Id::MUL_DD_HH => semantics::mul_dd_hh(),
            syntax::Id::MULA_DD_LL => semantics::mula_dd_ll(),
            syntax::Id::MULA_DD_HL => semantics::mula_dd_hl(),
            syntax::Id::MULA_DD_LH => semantics::mula_dd_lh(),
            syntax::Id::MULA_DD_HH => semantics::mula_dd_hh(),
            syntax::Id::MULS_DD_LL => semantics::muls_dd_ll(),
            syntax::Id::MULS_DD_HL => semantics::muls_dd_hl(),
            syntax::Id::MULS_DD_LH => semantics::muls_dd_lh(),
            syntax::Id::MULS_DD_HH => semantics::muls_dd_hh(),
            syntax::Id::MUL_AD_LL => semantics::mul_ad_ll(),
            syntax::Id::MUL_AD_HL => semantics::mul_ad_hl(),
            syntax::Id::MUL_AD_LH => semantics::mul_ad_lh(),
            syntax::Id::MUL_AD_HH => semantics::mul_ad_hh(),
            syntax::Id::MULA_AD_LL => semantics::mula_ad_ll(),
            syntax::Id::MULA_AD_HL => semantics::mula_ad_hl(),
            syntax::Id::MULA_AD_LH => semantics::mula_ad_lh(),
            syntax::Id::MULA_AD_HH => semantics::mula_ad_hh(),
            syntax::Id::MULS_AD_LL => semantics::muls_ad_ll(),
            syntax::Id::MULS_AD_HL => semantics::muls_ad_hl(),
            syntax::Id::MULS_AD_LH => semantics::muls_ad_lh(),
            syntax::Id::MULS_AD_HH => semantics::muls_ad_hh(),
            syntax::Id::MULA_DA_LL_LDINC => semantics::mula_da_ll_ldinc(),
            syntax::Id::MULA_DA_HL_LDINC => semantics::mula_da_hl_ldinc(),
            syntax::Id::MULA_DA_LH_LDINC => semantics::mula_da_lh_ldinc(),
            syntax::Id::MULA_DA_HH_LDINC => semantics::mula_da_hh_ldinc(),
            syntax::Id::MULA_DA_LL_LDDEC => semantics::mula_da_ll_lddec(),
            syntax::Id::MULA_DA_HL_LDDEC => semantics::mula_da_hl_lddec(),
            syntax::Id::MULA_DA_LH_LDDEC => semantics::mula_da_lh_lddec(),
            syntax::Id::MULA_DA_HH_LDDEC => semantics::mula_da_hh_lddec(),
            syntax::Id::MUL_DA_LL => semantics::mul_da_ll(),
            syntax::Id::MUL_DA_HL => semantics::mul_da_hl(),
            syntax::Id::MUL_DA_LH => semantics::mul_da_lh(),
            syntax::Id::MUL_DA_HH => semantics::mul_da_hh(),
            syntax::Id::MULA_DA_LL => semantics::mula_da_ll(),
            syntax::Id::MULA_DA_HL => semantics::mula_da_hl(),
            syntax::Id::MULA_DA_LH => semantics::mula_da_lh(),
            syntax::Id::MULA_DA_HH => semantics::mula_da_hh(),
            syntax::Id::MULS_DA_LL => semantics::muls_da_ll(),
            syntax::Id::MULS_DA_HL => semantics::muls_da_hl(),
            syntax::Id::MULS_DA_LH => semantics::muls_da_lh(),
            syntax::Id::MULS_DA_HH => semantics::muls_da_hh(),
            syntax::Id::UMUL_AA_LL => semantics::umul_aa_ll(),
            syntax::Id::UMUL_AA_HL => semantics::umul_aa_hl(),
            syntax::Id::UMUL_AA_LH => semantics::umul_aa_lh(),
            syntax::Id::UMUL_AA_HH => semantics::umul_aa_hh(),
            syntax::Id::MUL_AA_LL => semantics::mul_aa_ll(),
            syntax::Id::MUL_AA_HL => semantics::mul_aa_hl(),
            syntax::Id::MUL_AA_LH => semantics::mul_aa_lh(),
            syntax::Id::MUL_AA_HH => semantics::mul_aa_hh(),
            syntax::Id::MULA_AA_LL => semantics::mula_aa_ll(),
            syntax::Id::MULA_AA_HL => semantics::mula_aa_hl(),
            syntax::Id::MULA_AA_LH => semantics::mula_aa_lh(),
            syntax::Id::MULA_AA_HH => semantics::mula_aa_hh(),
            syntax::Id::MULS_AA_LL => semantics::muls_aa_ll(),
            syntax::Id::MULS_AA_HL => semantics::muls_aa_hl(),
            syntax::Id::MULS_AA_LH => semantics::muls_aa_lh(),
            syntax::Id::MULS_AA_HH => semantics::muls_aa_hh(),
            syntax::Id::LDINC => semantics::ldinc(),
            syntax::Id::LDDEC => semantics::lddec(),
            syntax::Id::CALL0 => semantics::call0(),
            syntax::Id::CALL4 => semantics::call4(),
            syntax::Id::CALL8 => semantics::call8(),
            syntax::Id::CALL12 => semantics::call12(),
            syntax::Id::J => semantics::j(),
            syntax::Id::BZ => semantics::bz(),
            syntax::Id::BEQI => semantics::beqi(),
            syntax::Id::BNEI => semantics::bnei(),
            syntax::Id::BLTI => semantics::blti(),
            syntax::Id::BGEI => semantics::bgei(),
            syntax::Id::ENTRY => semantics::entry(),
            syntax::Id::BF => semantics::bf(),
            syntax::Id::BT => semantics::bt(),
            syntax::Id::LOOP => semantics::r#loop(),
            syntax::Id::LOOPNEZ => semantics::loopnez(),
            syntax::Id::LOOPGTZ => semantics::loopgtz(),
            syntax::Id::BNONE => semantics::bnone(),
            syntax::Id::BEQ => semantics::beq(),
            syntax::Id::BLT => semantics::blt(),
            syntax::Id::BLTU => semantics::bltu(),
            syntax::Id::BALL => semantics::ball(),
            syntax::Id::BBC => semantics::bbc(),
            syntax::Id::BBCI => semantics::bbci(),
            syntax::Id::BANY => semantics::bany(),
            syntax::Id::BNE => semantics::bne(),
            syntax::Id::BGE => semantics::bge(),
            syntax::Id::BGEU => semantics::bgeu(),
            syntax::Id::BNALL => semantics::bnall(),
            syntax::Id::BBS => semantics::bbs(),
            syntax::Id::BBSI => semantics::bbsi(),
            syntax::Id::MOVI_N => semantics::movi_n(),
            syntax::Id::BEQZ_N => semantics::beqz_n(),
            syntax::Id::BNEZ_N => semantics::bnez_n(),
            syntax::Id::BLTUI => semantics::bltui(),
            syntax::Id::BGEUI => semantics::bgeui(),
            syntax::Id::L32R_N => semantics::l32r_n(),
            syntax::Id::S32I_N => semantics::s32i_n(),
            syntax::Id::ADD_N => semantics::add_n(),
            syntax::Id::ADDI_N => semantics::addi_n(),
            syntax::Id::MOV_N => semantics::mov_n(),
            syntax::Id::RET_N => semantics::ret_n(),
            syntax::Id::RETW_N => semantics::retw_n(),
            syntax::Id::BREAK_N => semantics::break_n(),
            syntax::Id::NOP_N => semantics::nop_n(),
        }

        offset += instruction.size();

        unimplemented!()
    }
}

fn match_opcode_le(opcode: &[u8]) -> Result<syntax::Instruction, Error> {
    let op = (opcode.get(0).ok_or(Error::Eof).map(|v| *v)?,
              opcode.get(1).ok_or(Error::Eof).map(|v| *v)?,
              opcode.get(2).map_or(0, |v| *v));

    syntax::match_opcode((op.0, op.1, op.2)).map_err(Error::Syntax)
}

fn match_opcode_be(opcode: &[u8]) -> Result<syntax::Instruction, Error> {
    let op = (opcode.get(0).ok_or(Error::Eof).map(|v| *v)?,
              opcode.get(1).ok_or(Error::Eof).map(|v| *v)?,
              opcode.get(2).map_or(0, |v| *v));

    syntax::match_opcode((op.2, op.1, op.0)).map_err(Error::Syntax)
}
